### GET REQUEST
GET http://localhost:3000/myapi/lfo3nd7wqsh26

### POST REQUEST
POST   http://localhost:3000/myapi
# content-type: application/json

{
	"test" :"Hello"
}

### PUT REQUEST
PUT  http://localhost:3000/myapi
content-type: application/json

{
	"hello": "world",
	"my" : "live"
}

### DELETE REQUEST
DELETE  http://localhost:3000/myapi