### GET REQUEST
GET http://localhost:8080/lfu4vuri0.73zex587yxy


### POST REQUEST
POST http://localhost:8080
content-type: application/json

{
  "test": "xxxxxxxxxxxxxxxxxxxxxxxxx",
  "test_1": "test"
}


### PUT REQUEST
PUT http://localhost:8080/lfu4vuri0.73zex587yxy
content-type: application/json

{
	"hello":"world",
  "Hi":" You"
}

### DELETE REQUEST
DELETE http://localhost:8080/lfu4pxnj0.d2krhh99tj6