### GET REQUEST
GET http://localhost:8080/lfrnffif0.9hhb7qeyhxo


### POST REQUEST
POST http://localhost:8080
content-type: application/json

{
  "test": "xxxxxxxxxxxxxxxxxxxxxxxxx",
  "test_1": "test"
}


### PUT REQUEST
PUT http://localhost:8080/lfu3keul0.ntfkxzq1ql
content-type: application/json

{
	"hello":"world"
}

### DELETE REQUEST
DELETE http://localhost:8080/lfu4pxnj0.d2krhh99tj6