### GET REQUEST
GET http://localhost:8080/lfu4vuri0.73zex587yxy


### POST REQUEST
POST http://localhost:8080
content-type: application/json

{
  "test": "xxxxxxxxxxxxxxxxxxxxxxxxx",
  "test_1": "test"
}


### PUT REQUEST
PUT http://localhost:8080/lfybtt1z0.2gaur519tdi
content-type: application/json

{
	"hello":"world",
  "Hi":" You"
}

### DELETE REQUEST
DELETE http://localhost:8080/lg00okty0.jlagv6xyeha